### ISSUE TITLE
new NumberTable(arg) does not work when arg is 2D array

### ISSUE THREAD

**Issue by Jeff-Clark** [moebiolabs/moebio_framework#224]
This issue was originally opened in modular_platform. I moved it here where it belongs.

See example lichen project jeff/bug/2DArray

Two different bugs I think:
1. Creating a numberTable from a 2D array does not work.
2. Also, it modifies the input to be a NumberList with NaN values which can be a nasty unexpected side-effect

**Comment by Jeff-Clark** [comment]
Comments from @moebio:
@Jeff-Clark Before tackling this issue, I'd like to know how do you think NumberTable could be instantiated, which different params it could accept (and how to interpret them, in case there's ambiguity).

(Once we solve NumberTable we can then move to other data types, I believe there's no coherent rule, and probably similar issues in other data types)

**Comment by Jeff-Clark** [comment]
I think at a minimum we should support:
1. var nT = new mo.NumberTable();
This creates an empty numberTable

2. var nT = new mo.NumberTable(anotherNumberTable);
Should do same as var nT = anotherNumberTable.clone();

3. var nT = new mo.NumberTable([[1,1,1],[2,2,2],[3,3,3],[4,4,4]]);
Should create a numberTable with 4 cols and 3 rows

4. var nT = new mo.NumberTable([nL1,nL2,nL3]);
Where nLi are numberLists should create a numberTable containing each numberList

And I also think the operation should never modify the arguments passed in.

We could maybe do something reasonable with:
5. var nT = new mo.NumberTable(nL1)
could make numberTable with a single column but ([L1]) is more clear for that case.
Also (nCols,nRows) might be useful but we can use TableGenerators.createTableWithSameElement for that already.

**Comment by moebio** [comment]
@Jeff-Clark This is great
I find 2. and 3. very interesting, as intuitive alternatives to clone and fromArray. 
5. makes sense to me

This you know, but worth be stated: not only instantiation should not modify received parameters, as you mention, but also they shouldn't be directly used. For instance in 4., the lists of the new table should be clones of the received lists, not the lists themselves, so the new table is a completely independent instance.


-------

The spectrum of possible parameters that make sense augment if we take into account receiving more than one. I'd add:

6. var nT = new mo.NumberTable(nL1, nL2,…)

7. same with arrays with numbers, instead of #L

8. maybe also just numbers nT = new mo.NumberTable(n1, n2,…) that will behave similar to 5., creating a table with just one column


What I like from this, is that it's somehow replicable, or at least it gives a sort of guidance, for making the similar work on other data types in a coherent way. (the most complicate, I think, will be List, for there could be ambiguities).


Do you want to deploy these changes?

**Comment by Jeff-Clark** [comment]
@moebio I'm happy to do it but I'm pretty deep in the big data work at the moment so it will be a couple more days until I tackle it.

**Comment by moebio** [comment]
assigned @Javingka to this task

**Comment by Javingka** [comment]
Updates done. details on the pull-request ref #225
